#### REQUIRED ####
bam: "/path/to/bam"  # path to the alignments BAM or CRAM file
bed: "/path/to/gt_bed_or_vcf"  # path to the ground truth BED or VCF file
fai: "/path/to/fai"  # path to the referene FASTA FAI file
#### OPTIONAL ####
n_cpus: 1 # number of CPUs (parallelized by chromosome)
chr_names: null # list of chromosomes to process: null (all) or a specific list e.g. ["chr1", "chr21"]
allow_empty: False
empty_annotation: False
#### FIXED ####
scan_target_intervals: False
stream: False
store_img: True
bam_type: "SHORT"
signal_set: "SHORT"
signal_set_origin: "SHORT"
class_set: "BASIC5ZYG"
signal_vmax: {"RD": 600, "RD_LOW": 800, "RD_CLIPPED": 600, "SM": 200, "SR_RP": 600, "LR": 600, "LLRR": 100, "RL": 100, "LLRR_VS_LR": 1}
signal_mapq: {"RD": 20, "RD_LOW": 0, "RD_CLIPPED": 20, "SM": 20, "SR_RP": 0, "LR": 0, "LLRR": 1, "RL": 1, "LLRR_VS_LR": 1}
bin_size: 750
interval_size: 150000
step_size: 50000
shift_size: [0, 75000, 150000]
heatmap_dim: 1000
image_dim: 256
num_keypoints: 1
bbox_padding: 0
