#### REQUIRED ####
bam: "/path/to/bam"  # path to the alignments BAM or CRAM file
bed: "/path/to/gt_bed_or_vcf"  # path to the ground truth BED or VCF file
fai: "/path/to/fai"  # path to the referene FASTA FAI file
#### OPTIONAL ####
n_cpus: 1 # number of CPUs (parallelized by chromosome)
chr_names: null # list of chromosomes to process: null (all) or a specific list e.g. ["chr1", "chr21"]
allow_empty: False
empty_annotation: False
scan_target_intervals: False
stream: False
store_img: True
